### ISSUE TITLE
Missing fragments

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad22-practical-3---event-handling-yongziren#2]
https://github.com/MAD11877/mad22-practical-3---event-handling-yongziren/blob/13ee541a646e5254e8078933792086abd4e532f5/app/src/main/java/sg/edu/np/mad/madpractical/MessageGroup.java#L20-L36

You will need to use fragments here
although they seems to achieve similar results, the practical is simplified so that you get a flavour of what is fragments. otherwise you will need to implement alot of fragments to justify the usage

**Comment by New-President** [comment]
fixed issue
